# Rotation matrixes 
--- 
In the given lesson we defined several coordinate frames: World frame, Body frame, and wind frame. 

In the past term, we covered the conversion between two frames in detail. Thus in this exercise, we will go through the two-dimensional matrix transformation which is mathematically simple. But will provide an excellent practice to develop better an intuitive understanding of these frames and how they are related to each other.

In [3]:
from math import sin, cos
import numpy as np 

<img src="Frames.png" width="800">

In [5]:
# simple rotation matrix in 2D 
def rotation_matrix(angle):
    '''
    Rotation matrix function
    args: 
        angle: angle of rotation
    returns: 
        rotation matrix 
    '''
    r = np.matrix([[cos(angle), -sin(angle)],
                  [sin(angle),  cos(angle)]])
    return r 

As an exercise define rotation matrixes for the world frame to the body frame of reference, the world frame of reference to the wind frame of reference, wind frame of reference to the body frame of reference in terms of the rotation matrix. Finally, make sure that the given matrix truly perform correct transformations. 

For the given exercise we will assume that $\theta = -5^{\circ}$, $\gamma = 2^{\circ}$

In [6]:
theta = 5/180*np.pi
gamma = -2/180*np.pi

# TODO: Declare matrix corresponding transformation between frames by placing the proper angle
r_world_to_body = rotation_matrix(theta)
r_world_to_wind = rotation_matrix(-gamma)
r_wind_to_body = rotation_matrix(gamma + theta)
r_body_to_world = rotation_matrix(-theta)
r_wind_to_world = rotation_matrix(gamma)


As a test transform frames from the world to the wind and then from the wind to the body frame and make sure that it is the same as the transformation from the world frame to the body. 

In [7]:
r_x = r_wind_to_body @ r_world_to_wind
print('Combined rotation matrix is: \n',r_x)
print('Direct rotation matrix is: \n',r_world_to_body)

Combined rotation matrix is: 
 [[ 0.9961947  -0.08715574]
 [ 0.08715574  0.9961947 ]]
Direct rotation matrix is: 
 [[ 0.9961947  -0.08715574]
 [ 0.08715574  0.9961947 ]]


For a next step let us consider a simple drone with a mass of 1 [kg], which developed thrust of 2 [N], while lift and the drag forces are 10[N] and 1.5 [N]. 

Calculate the linear acceleration in the world frame. Note that the values are given in different are measured in different frames. 

<img src="Forces.png" width="400">

In [8]:
mass= 1.0
thrust = 2.0
lift = 10.0
drag = 1.5 
g = 9.8

# TODO: Convert the given scalar values into vectors
weight_vec = np .array([[0], [-g*mass]])
thrust_vec = r_body_to_world * np.array([[thrust], [0]])
lift_vec = r_wind_to_world * np.array([[0], [lift]])
drag_vec = r_wind_to_world * np.array([[-drag],[0]])

In [6]:
weight_vec

array([[ 0. ],
       [-9.8]])

In [9]:
thrust_vec

matrix([[ 1.9923894 ],
        [-0.17431149]])

In [10]:
lift_vec

matrix([[ 0.34899497],
        [ 9.99390827]])

In [11]:
drag_vec

matrix([[-1.49908624],
        [ 0.05234925]])

Since

\begin{align}
    F = m\circ A
\end{align}

we find from

\begin{align}
T - D &= m \circ A
\end{align}

That

\begin{align}
A &= \frac{T - D}{m}
\end{align}

Note that because $W = \left[ \begin{matrix} 0 \\ -g \cdot m \end{matrix} \right]$ and since $W$ is always in world coordinates, we just have $\frac{W}{g} = \left[ \begin{matrix} 0 \\ -m \end{matrix} \right]$.

In [26]:
weight_vec / g

array([[ 0.],
       [-1.]])

In [25]:
thrust_vec - drag_vec

matrix([[ 3.49147564],
        [-0.22666073]])

In [35]:
# TODO: Calculate the linear acceleration of the drone in world frame 
a_world = (thrust_vec - drag_vec) / mass

In [36]:
print('Horizontal acceleration is %.2f [m/s^2]'%a_world[0])
print('Vertical acceleration is %.2f [m/s^2]'%a_world[1])

Horizontal acceleration is 3.49 [m/s^2]
Vertical acceleration is -0.23 [m/s^2]
